CREATE TABLE `Product` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50),
  `price` DECIMAL(12,2),
  PRIMARY KEY (`id`)
);
INSERT INTO `Product` (`name`, `price`) VALUES ('Amoi F99b', 100.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('BenQ-Siemens C81', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Ericsson T29s', 40.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Acer Iconia Tab A101', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Toshiba 904T', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Parla Mist', 40.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Microsoft Lumia 950', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('ZTE S213', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Honor 20 Pro', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Benefon Esc!', 10.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Spice Stellar 526 (Mi-526)', 70.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('i-mobile 520', 50.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Icemobile Fuego', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('YU Yureka S', 10.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Modu Mini jacket', 10.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Asus ROG Phone 3 Strix', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Acer Iconia Tab A3-A20FHD', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Micromax X370', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('BLU Touch Book 7.0 Plus', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Modu Night jacket', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Plum Axe 4', 40.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Spice Mi-423 Smart Flo Ivory 2', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('alcatel OT-E158', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Motorola V80', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('verykool i130', 10.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Xiaomi Mi Mix Alpha', 100.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('HP TouchPad', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Sonim XP1300 Core', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Nokia C5', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Celkon A63', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Asus Transformer Pad TF701T', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Gigabyte g-Cam', 40.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('T-Mobile Move Balance', 50.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Asus Zenfone 2 Deluxe ZE551ML', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Huawei Ascend G526', 50.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Lenovo Yoga Tablet 8', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Sony Ericsson Yari', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Kyocera TG 200', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Mitac MIO Explora K70', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Celkon C5050 Star', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Toshiba Thrive 7', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('T-Mobile REVVL 5G', 50.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('BenQ-Siemens S68', 70.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Oppo F11', 10.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Apple iPhone 6s', 100.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Eten glofiish DX900', 70.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('verykool s810', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Sagem MY X5-2', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('VK Mobile VK540', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Maxwest Orbit 5400T', 100.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Meizu 15 Lite', 40.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('HTC Rider', 40.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Plum Axe Plus', 100.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Meizu M1 Metal', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Sendo Z100', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('XOLO A500 Club', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Coolpad Porto', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('O2 XDA Star', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Sagem RC 730', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Xiaomi Mi Pad 7.9', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('BenQ-Siemens EF71', 50.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Motorola Talkabout T192', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Plum Axe II', 100.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Cat B35', 10.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Casio G''zOne Brigade', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Unnecto Shell', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Amazon Fire HD 10 (2017)', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Meizu Pro 6s', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Eten M500', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Innostream INNO 90', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Oppo K1', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Philips Xenium 9@9t', 50.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('HP iPAQ rw6828', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Lenovo LePad S2005', 40.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Micromax X215', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Samsung Galaxy A6+ (2018)', 50.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Spice Mi-449 3G', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('BenQ T51', 70.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Ericsson GH 218', 80.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Sharp TM200', 40.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Huawei U1310', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Dell Venue 10 7000', 70.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Coolpad Cool M7', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('O2 XDA Serra', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Karbonn KT21 Express', 100.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('i-mate PDA2', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Innostream INNO 75', 90.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Vertu Ascent Ti', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Allview P2 AllDro', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Emporia Solid Plus', 40.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('HP 7 VoiceTab', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Ulefone S11', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Pantech G300', 10.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Eten glofiish X500+', 60.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Parla Minu P123', 100.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Prestigio MultiPhone 3400 Duo', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Celkon C66+', 30.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Kyocera E3500', 20.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('Emporia Click Plus', 10.00);
INSERT INTO `Product` (`name`, `price`) VALUES ('BQ Aquaris M4.5', 60.00);